tasks:
  - name: Python modules
    before: pip install requirements.txt

ports:
  - port: 9000-9999 # Jupyter ports
    onOpen: ignore
      
vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
    - mhutchie.git-graph
